development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  channel_prefix: chat_app_production
  url: redis://redistogo:4e093a9a0875501c7e781442c04d25b3@hammerjaw.redistogo.com:11730/
